# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/#customizing-settings
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Container Scanning customization: https://docs.gitlab.com/ee/user/application_security/container_scanning/#customizing-the-container-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence

# 1. choose a running method `deploy_pubsub` or `deploy_http`
# 2. replace [GCF-NAME] and optionally [PUBSUB-TOPIC-NAME] when PubSub handler is used
# 3. please choose right memory and timeout

stages:
- test
- deploy

sast:
  stage: test
include:
- template: Security/SAST.gitlab-ci.yml

deploy_production:
  image: google/cloud-sdk:slim
  stage: deploy
  script:
    - deploy_pubsub statuspage-manager statuspage-manager-alert
  only:
    - main

.utils: &utils |
  # FCE name, topic name
  function deploy_pubsub() {
    gcloud beta functions deploy $1 --region=europe-west2 --source=./src/ \
      --runtime='php81' \
      --gen2 \
      --ingress-settings="internal-only" \
      --memory='512MB' \
      --timeout='60s' \
      --max-instances='5' \
      --entry-point='main' \
      --trigger-topic=$2
  }

before_script:
  - *utils

